### ISSUE TITLE
Offset bindi position too far to the right, needs to move left a little

### ISSUE THREAD

**Issue by bhajneet** [GurbaniNow/gurmukhi-fonts#1]
![image](https://user-images.githubusercontent.com/14130567/65390434-d4ccc580-dd2c-11e9-9502-997f1160bfbd.png)

See in highlighted line above for word Chhee(n)bai

**Comment by sarabveer** [comment]
I increased the spacing a little, but can't do much otherwise breaking spacing for other akhars.
