### ISSUE TITLE
Adjust pair vavva + aunkar

### ISSUE THREAD

**Issue by bhajneet** [GurbaniNow/gurmukhi-fonts#10]
See ShabadOS/database/issues/1443 for example

**Comment by sarabveer** [comment]
Black:
![image](https://user-images.githubusercontent.com/4297171/77853459-337a6c80-71b2-11ea-89ee-6510f9d9672a.png)


Bold:
![image](https://user-images.githubusercontent.com/4297171/77837714-40f41000-713a-11ea-8be8-1450309634f4.png)

Regular:
![image](https://user-images.githubusercontent.com/4297171/77837723-56693a00-713a-11ea-9f52-e2903afee185.png)
