### ISSUE TITLE
Suggested ASCII mapping for open-form yaiya akhars

### ISSUE THREAD

**Issue by irvanjitsingh** [GurbaniNow/gurmukhi-fonts#11]
**half-yaiya, open-top**: î (similar to the character for closed-top half-yaiya)
**full yaiya, open-top**: ï (adjacent to u00EF)

**Comment by sarabveer** [comment]
Related to #9

**Comment by bhajneet** [comment]
What is the benefit to changing them?

**Comment by sarabveer** [comment]
@irvanjitsingh `ï` is U+00EF
