### ISSUE TITLE
Add lookups for subscripted ਅੰਕ (numerals) found under some sirlekhs

### ISSUE THREAD

**Issue by irvanjitsingh** [GurbaniNow/gurmukhi-fonts#2]
All fonts based on AnmolUniBani already contain glyphs representing these ank and are currently mapped to unused code points F045 through F051.

Example:

ਰਾਗੁ ਗਉੜੀ ਪੂਰਬੀ ਮਹਲਾ ੫ 
ਰਾਗੁ ਗਉੜੀ ਪੂਰਬੀ ਮਹਲਾ ੫

renders as 

![image](https://user-images.githubusercontent.com/1472548/67919997-ecdc0400-fb78-11e9-904a-c11a7e8300cf.png)

**Suggestion**: add lookup entries for (virama + number) to make these easier to use and renderable as normal numerals if the correct font isn't available.

Example:
੍ + ੧ = 
੍ + ੍ + ੧ = 

**Comment by sarabveer** [comment]
The only problem with this is that if correct font isn't available, it will still display oddly.

> ਰਾਗੁ ਗਉੜੀ **ਪੂਰ੍੧ਬੀ** ਮਹਲਾ ੫

This could possibly create confusion. As a better approch, we could put these anks and reference them in the notes section of the Shabad OS [database](https://github.com/ShabadOS/database) as SGPC has done in their shabad arth.

Would be better to submit this as a proposal so software vendors/OEMs can also update their fonts (or at least be notified).

**Comment by irvanjitsingh** [comment]
Our database has had them for a while (with an explanation in the teekaa) but instead of placing it in the middle of the word it's been placed at the end (because there was no font solution).

![IMG_2558](https://user-images.githubusercontent.com/1472548/69580166-0ae32b80-0fa2-11ea-938c-6b03c0206f22.PNG)

**Comment by sarabveer** [comment]
![image](https://user-images.githubusercontent.com/4297171/69776380-023d5180-116a-11ea-8037-7c27f9d723b3.png)


![image](https://user-images.githubusercontent.com/4297171/69776361-ee91eb00-1169-11ea-9168-42a3fa91b5d1.png)

**Comment by sarabveer** [comment]
![image](https://user-images.githubusercontent.com/4297171/69776439-3dd81b80-116a-11ea-9a7b-ed2902731b75.png)
