### ISSUE TITLE
Half-yaiya doesn't render properly if placed after a bihari

### ISSUE THREAD

**Issue by irvanjitsingh** [GurbaniNow/gurmukhi-fonts#3]
cqur byd piTXM kIÎo kwis bwsM ]
ਚਤੁਰ ਬੇਦ ਪਠਿਯੰ ਕੀ੍ਯੋ ਕਾਸਿ ਬਾਸੰ ॥

**Comment by sarabveer** [comment]
@irvanjitsingh can you give a count of occurrences?

Shabad OS has the tuk as `ਚਤੁਰ ਬੇਦ ਪਠਿਯੰ ਕੀਯੋ ਕਾਸਿ ਬਾਸੰ ॥`

**Comment by sarabveer** [comment]
Need to check if this is a rendering issue or a font issue, here are some combinations:

`ਕੀ੍ਯੋ`
`ਕ੍ਯੀੌ`

I know for `ਭ੍ਯਿੋ`, the sihari has to be after the half-yaiya, otherwise it renders as `ਭਿ੍ਯੋ`

https://github.com/ShabadOS/gurmukhi-utils/issues/63

**Comment by sarabveer** [comment]
Would also need to check on multiple platforms:

https://github.com/ShabadOS/gurmukhi-utils/issues/28

**Comment by sarabveer** [comment]
Seems like this is a font render issue, will need to check if lookups work to fix this on all platforms (ex. bindi-bihari lookup only works in browser)
