### ISSUE TITLE
Rendering issue with ਪੈਰੀਂ ਬਿੰਦੀ for loan letters for ASCII and unicode

### ISSUE THREAD

**Issue by irvanjitsingh** [GurbaniNow/gurmukhi-fonts#6]
UNICODE: 
ਲ + ਼ should render the same as ਲ਼, (bindi to the left of the letter) current it doesn't. As should every other combination (particularly ਕ+਼)

ASCII:
s + æ should render the same as S, j + æ as z, etc.

**Comment by sarabveer** [comment]
In which font does this occur? OpenSatluj has a lookup for `ਲ + ਼`.

Not sure if every akhar needs a special glyph for pair-bindi, any reason why `ਕ+਼` would need a special glyph?

**Comment by sarabveer** [comment]
Oh nvm, you are referring the placement of the bindi itself.

> s + æ should render the same as S, j + æ as z, etc.

lookups can be added to gurbaniakhar font
