### ISSUE TITLE
Add yaiya with open top character to font

### ISSUE THREAD

**Issue by bhajneet** [GurbaniNow/gurmukhi-fonts#9]
Required for Sri Dasam Granth. Will link multiple issues later.

**Comment by sarabveer** [comment]
`ì` (U+00EC) -> full yaiyha with no line over top
`í` (U+00ED) -> adha-yaiyha with no line over top

**Comment by sarabveer** [comment]
Black:
![image](https://user-images.githubusercontent.com/4297171/77837780-02128a00-713b-11ea-88d8-6ce6455337cb.png)

Bold:
![image](https://user-images.githubusercontent.com/4297171/77837783-0fc80f80-713b-11ea-9bca-63fc0c834a7d.png)

Regular:
![image](https://user-images.githubusercontent.com/4297171/77837766-f0c97d80-713a-11ea-8199-145ac83cd30e.png)
